# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# @dep = Department.create(name: 'Human Resource', short_name: 'HR')
# Employee.create(first_name: 'shema', last_name: 'prince', email: 'admin@gmail.com', birth_date: Time.current, password: 'prince', admin: 'true', department_id: @dep.id)
# Employee.create(first_name: 'shema', last_name: 'prince', email: 'shema@gmail.com', birth_date: Time.current, password: 'prince',  admin: 'true', department_id: @dep.id)
# Employee.create(first_name: 'aimable', last_name: 'ndiku', email: 'ndiku@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'shamil', last_name: 'jason', email: 'admin2@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'cadet', last_name: 'Prince', email: 'cadet@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'alicia', last_name: 'prince', email: 'alicia@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'soki', last_name: 'prince', email: 'soki@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'shema', last_name: 'prince', email: 'admin1@gmail.com', birth_date: Time.current, password: 'prince', admin: 'true', department_id: @dep.id)
# Employee.create(first_name: 'shamil', last_name: 'gisa', email: 'shami@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'aimable', last_name: 'ndiku', email: 'armel@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'shamil', last_name: 'jason', email: 'aimable@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'cadet', last_name: 'shamil', email: 'candy@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'alicia', last_name: 'prince', email: 'graciela@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
# Employee.create(first_name: 'soki', last_name: 'prince', email: 'gai@gmail.com', birth_date: Time.current, password: 'prince', department_id: @dep.id)
@em = Employee.first
Department.create(name: 'Human Resource', short_name: 'HR')
Department.create(name: 'Finance Department', short_name: 'FD')
Department.create(name: 'Food and Drink beverages', short_name: 'F&D')
Department.create(name: 'Human Resource', short_name: 'HR')
Department.create(name: 'Finance Department', short_name: 'FD')
Department.create(name: 'Control Market', short_name: 'F&D')
Department.create(name: 'Programming Department', short_name: 'PD')
Department.create(name: 'Food and Drinks Dinner', short_name: 'FDD')
Department.create(name: 'Human Resource branch', short_name: 'HRB')
Department.create(name: 'Human Resource Academey', short_name: 'HR')
Department.create(name: 'Academy Bridge', short_name: 'AB')
Department.create(name: 'Sport Department', short_name: 'S&D')
Department.create(name: 'Home Department', short_name: 'HD')
Department.create(name: 'Sleep Department', short_name: 'SD')
Department.create(name: 'Show Department', short_name: 'F&D')
Department.create(name: 'Yes Department', short_name: 'HR')
Department.create(name: 'Analyse Department', short_name: 'AD')
Department.create(name: 'Short Meatings', short_name: 'S&M')
Department.create(name: 'Prince Department', short_name: 'PD')
Department.create(name: 'Shamil Department', short_name: 'SD')

Leafe.create(leave_type: 'Illiness', description: 'I am not fealing well', employee_id: @em.id)
Leafe.create(leave_type: 'Personal issue', description: 'I am not doing well', employee_id: @em.id)
Post.create(title: 'Tomorrow no work', content: 'I am not doing well', employee_id: @em.id)