# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
@dep = Department.create(name: 'Human Resource', short_name: 'HR')
Employee.create!(first_name: 'shema', last_name: 'prince', email: 'admin@gmail.com', password: 'prince', admin: 'true', department_id: @dep.id)
Employee.create(first_name: 'shema', last_name: 'prince', email: 'shema@gmail.com', password: 'prince',  admin: 'true', department_id: @dep.id)
Employee.create(first_name: 'aimable', last_name: 'ndiku', email: 'ndiku@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'shamil', last_name: 'jason', email: 'admin2@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'cadet', last_name: '', email: 'cadet@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'alicia', last_name: 'prince', email: 'alicia@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'soki', last_name: 'prince', email: 'soki@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create!(first_name: 'shema', last_name: 'prince', email: 'admin1@gmail.com', password: 'prince', admin: 'true', department_id: @dep.id)
Employee.create(first_name: 'shamil', last_name: 'gisa', email: 'shami@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'aimable', last_name: 'ndiku', email: 'armel@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'shamil', last_name: 'jason', email: 'aimable@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'cadet', last_name: '', email: 'candy@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'alicia', last_name: 'prince', email: 'graciela@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'soki', last_name: 'prince', email: 'gai@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create!(first_name: 'shema', last_name: 'prince', email: 'grace@gmail.com', password: 'prince', admin: 'true', department_id: @dep.id)
Employee.create(first_name: 'shema', last_name: 'prince', email: 'kuku@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'aimable', last_name: 'ndiku', email: 'mimi@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'shamil', last_name: 'jason', email: 'nadia@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'cadet', last_name: '', email: 'darem@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'alicia', last_name: 'prince', email: 'blise@gmail.com', password: 'prince', department_id: @dep.id)
Employee.create(first_name: 'soki', last_name: 'prince', email: 'nadeje@gmail.com', password: 'prince', department_id: @dep.id)
Department.create(name: 'Human Resource', short_name: 'HR')
Department.create(name: 'Finance Department', short_name: 'FD')
Department.create(name: 'Food and Drink beverages', short_name: 'F&D')
Department.create(name: 'Human Resource', short_name: 'HR')
Department.create(name: 'Finance Department', short_name: 'FD')
Department.create(name: 'Control Market', short_name: 'F&D')
Department.create(name: 'Programming Department', short_name: 'PD')
Department.create(name: 'Food and Drinks Dinner', short_name: 'FDD')
Department.create(name: 'Human Resource branch', short_name: 'HRB')
Department.create(name: 'Human Resource Academey', short_name: 'HR')
Department.create(name: 'Academy Bridge', short_name: 'AB')
Department.create(name: 'Sport Department', short_name: 'S&D')
Department.create(name: 'Home Department', short_name: 'HD')
Department.create(name: 'Sleep Department', short_name: 'SD')
Department.create(name: 'Show Department', short_name: 'F&D')
Department.create(name: 'Yes Department', short_name: 'HR')
Department.create(name: 'Analyse Department', short_name: 'AD')
Department.create(name: 'Short Meatings', short_name: 'S&M')
Department.create(name: 'Prince Department', short_name: 'PD')
Department.create(name: 'Shamil Department', short_name: 'SD')